# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# area_solar_radiation.py
# Created on: 2014-03-08 13:55:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

http://resources.arcgis.com/en/help/main/10.2/index.html#//001w00000009000000
# ...coordinates that define the extent in the coordinate system in which the input data is stored.
# Set the extent environment using the Extent class.
# arcpy.env.extent = arcpy.Extent(-107.0, 38.0, -104.0, 40.0)


# Local variables:
DSM_4342-01-25_c_a_img = "C:\\Users\\stuporglue\\Documents\\GitHub\\solar_scripts\\arcdata\\DSM_4342-01-25_c_a.img"
gradraster = "C:\\Users\\stuporglue\\Documents\\GitHub\\solar_scripts\\arcdata\\outputs\\gradraster"
dradraster = "C:\\Users\\stuporglue\\Documents\\GitHub\\solar_scripts\\arcdata\\outputs\\dradraster"
difradraster = "C:\\Users\\stuporglue\\Documents\\GitHub\\solar_scripts\\arcdata\\outputs\\difradraster"
dirdurraster = "C:\\Users\\stuporglue\\Documents\\GitHub\\solar_scripts\\arcdata\\outputs\\dirdurraster"

# Process: Area Solar Radiation
# http://resources.arcgis.com/en/help/main/10.2/index.html#//009z000000t5000000
# AreaSolarRadiation (in_surface_raster, {latitude}, {sky_size}, {time_configuration}, {day_interval}, {hour_interval}, {each_interval}, {z_factor}, {slope_aspect_input_type}, {calculation_directions}, {zenith_divisions}, {azimuth_divisions}, {diffuse_model_type}, {diffuse_proportion}, {transmittivity}, {out_direct_radiation_raster}, {out_diffuse_radiation_raster}, {out_direct_duration_raster})

args = {
        "in_surface_raster": None,
        "latitude": None,
        "sky_size": 200,
        "time_configuration": 'MultiDays 2014 1 365',
        "day_interval": 14,
        "hour_interval": 0.5,
        "each_interval": 'NOINTERVAL',
        "z_factor": 1,
        "slope_aspect_input_type": 'FROM_DEM',
        "calculation_directions": 32,
        "zenith_divisions": 8,
        "azimuth_divisions": 8,
        "diffuse_model_type": 'UNIFORM_SKY',
        "diffuse_proportion": 0.3,
        "transmittivity": 0.5,
        "out_direct_radiation_raster": None,
        "out_diffuse_radiation_raster": None,
        "out_direct_duration_raster": None,
}

AreaSolarRadiation(DSM_4342-01-25_c_a_img,
        gradraster,                   # Global radiation raster
        "44.980436239969",            # Latitude
        "200",                        # Sky size
        "MultiDays   2014  120  150", # 120 / 150 are start and end days
        "14",                         # Day interval
        "0.5",                        # Hour interval
        "NOINTERVAL",                 #  
        "1",
        "FROM_DEM",
        "32",
        "8",
        "8",
        "UNIFORM_SKY",
        "0.3",
        "0.5",
        dradraster,                   # direct radiation raster
        difradraster,                 # Difuse radiation raster  
        dirdurraster                  # Direct duration raster
        )
