#!/bin/bash -l

# Max time the job will run for
#PBS -l walltime=15:00:00

# Amount of memory per core/job 
#PBS -l pmem=2500mb

# Number of nodes we're asking for and number of proc
#PBS -l nodes=300:ppn=8

# Send mail (-m) when the job is (a)borted, (b)egins and (e)nds
#PBS -m abe
#####  P B   S  -l pmem=2500mb,nodes=2:ppn=8,pmem=4gb,walltime=24:00:00

# Run 8 instances of batchSolarAnalyst
pbsdsh -c 8 /home/lenkne/shared/solar_scripts/qsub/batchSolarAnalyst.sh 2>&1 >> output &
wait
